export const mockProducts = [
  {
    id: "1",
    name: "Dell XPS 15 9530",
    category: "computers",
    brand: "Dell",
    sku: "DXPS-15-9530",
    description: "High performance laptop with beautiful display.",
    specifications: { "RAM": "16GB", "Storage": "1TB SSD", "Processor": "Intel Core i7" },
    price_rwf: 1800000,
    price_usd: 1500,
    images: ["https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=400&q=80"],
    in_stock: true,
    featured: true,
  },
  {
    id: "2",
    name: "HP Elitebook 840 G8",
    category: "computers",
    brand: "HP",
    sku: "HPE-840-G8",
    description: "Business oriented reliable laptop.",
    specifications: { "RAM": "8GB", "Storage": "512GB SSD", "Processor": "Intel Core i5" },
    price_rwf: 900000,
    price_usd: 750,
    images: ["https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=400&q=80"],
    in_stock: true,
    featured: true,
  },
  {
    id: "3",
    name: "Cisco Catalyst 9200",
    category: "networking",
    brand: "Cisco",
    sku: "CIS-CAT-9200",
    description: "Enterprise class 24-port switch layer 3 routing.",
    specifications: { "Ports": "24", "PoE": "Yes", "Speed": "Gigabit" },
    price_rwf: 1200000,
    price_usd: 1000,
    images: ["https://plus.unsplash.com/premium_photo-1681400813959-1cefa26bf3b9?auto=format&fit=crop&w=400&q=80"],
    in_stock: true,
    featured: false,
  },
  {
    id: "4",
    name: "Hikvision 4K IP Camera",
    category: "security",
    brand: "Hikvision",
    sku: "HIK-4K-IP",
    description: "Outdoor weatherproof security camera night vision.",
    specifications: { "Resolution": "4K", "Night Vision": "30m", "Type": "Bullet" },
    price_rwf: 120000,
    price_usd: 100,
    images: ["https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=400&q=80"],
    in_stock: false,
    featured: true,
  },
  {
    id: "5",
    name: "Samsung 27 inch Curved Monitor",
    category: "displays",
    brand: "Samsung",
    sku: "SAM-27C",
    description: "Immersive viewing experience with 144Hz refresh rate.",
    specifications: { "Size": "27 inch", "Refresh Rate": "144Hz", "Resolution": "1080p" },
    price_rwf: 300000,
    price_usd: 250,
    images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=400&q=80"],
    in_stock: true,
    featured: false,
  },
  {
    id: "6",
    name: "Logitech MX Master 3",
    category: "computers",
    brand: "Logitech",
    sku: "LOG-MX3",
    description: "Advanced wireless mouse.",
    specifications: { "Type": "Wireless", "Sensors": "Darkfield", "Battery": "70 days" },
    price_rwf: 140000,
    price_usd: 110,
    images: ["https://plus.unsplash.com/premium_photo-1661771746961-d00db6e30b35?auto=format&fit=crop&w=400&q=80"],
    in_stock: true,
    featured: false,
  },
];
